# Usa una imagen de Node.js oficial como base
FROM node:20-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de package.json y package-lock.json (si existe)
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia los archivos y carpetas del proyecto al directorio de trabajo del contenedor
COPY . .

# Set environment variables
ENV NODE_ENV=development
ENV REACT_APP_API_URL=http://localhost:3000/api

# Expone el puerto 4200
EXPOSE 4200

# Comando para ejecutar la aplicación
CMD ["npm", "run", "start:docker"]